name: $(Build.BuildId)

resources:
  repositories:
   - repository: origam-source
     type: github
     endpoint: https://github.com/origam/
     name: origam/origam-source
     ref: $(BRANCH)
   - repository: origam-html
     type: github
     endpoint: https://github.com/origam/
     name: origam/origam-html
     ref: $(BRANCH)
   - repository: origam-model
     type: github
     endpoint: https://github.com/origam/
     name: origam/origam-model
     ref: $(BRANCH)
   - repository: origam-html-chat
     type: github
     endpoint: https://github.com/origam/
     name: origam/origam-html-chat
     ref: $(BRANCH)


variables:
- name: NUGET_PACKAGES # location of nuget packages (used by cache)
  value: $(Pipeline.Workspace)/.nuget/packages
- name: YARN_CACHE_FOLDER # location of yarn cache
  value: $(Pipeline.Workspace)/.yarn
- name: BRANCH # branch to be used
  value: master
- name: VERSION_NUMBER # version number of the build
  value: 0.0.1.$(Build.BuildId)
- name: TAG # tag to be used
  value: master-latest


jobs:
  - job: BuildOrigam
    displayName: Build Origam
    pool:
      vmImage: windows-2019
    steps:
     - checkout: origam-source
       fetchDepth: 1
       persistCredentials: true
     - script: |
        git tag -f $(TAG)
       workingDirectory: $(Agent.BuildDirectory)\s\origam-source
       displayName: 'Tag origam-source with $(TAG)'
     - script: |
        git push -f origin $(TAG)
       workingDirectory: $(Agent.BuildDirectory)\s\origam-source
       displayName: 'Tag origam-source with $(TAG)'
     - checkout: origam-html
       fetchDepth: 1
       persistCredentials: true
     - checkout: origam-model
       fetchDepth: 1
     - checkout: origam-html-chat
       fetchDepth: 1
     - powershell: |
         $commitId = (git -C $(Agent.BuildDirectory)\s\origam-source rev-parse HEAD)
         Write-Host $commitId
         Write-Host "##vso[task.setvariable variable=ORIGAM_SOURCE_COMMIT_ID;]$commitId"
       displayName: Store origam-source commit id
     - task: NuGetToolInstaller@0
       displayName: 'Use NuGet 5.8'
       inputs:
         versionSpec: 5.8
     - task: NodeTool@0
       displayName: 'Use Node 11.x'
       inputs:
         versionSpec: 11.x
     - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
       displayName: 'Use Yarn 1.x'
     - task: Cache@2
       displayName: 'NuGet Cache'
       inputs:
         key: 'nuget-2021-04-11-01 | "$(Agent.OS)" | $(Agent.BuildDirectory)/s/origam-source/**/*.sln,!$(Agent.BuildDirectory)/s/origam-source/**/bin/**'
         path: '$(NUGET_PACKAGES)'
         restoreKeys: 'nuget-2021-04-11-01 | "$(Agent.OS)"'
     - task: Cache@2
       displayName: 'Yarn Cache'
       inputs:
         key: 'yarn-2021-04-08-01 | "$(Agent.OS)" | $(Agent.BuildDirectory)/s/origam-html/yarn.lock,$(Agent.BuildDirectory)/s/origam-html-chat/yarn.lock'
         path: '$(YARN_CACHE_FOLDER)'
         restoreKeys: 'yarn-2021-04-08-01 | "$(Agent.OS)"'
     - task: NuGetCommand@2
       displayName: 'NuGet restore'
       inputs:
         command: 'restore'
         restoreSolution: '$(Agent.BuildDirectory)/s/origam-source/**/*.sln'
         feedsToUse: 'select'
     - powershell: |
        $fileName = Get-ChildItem "**\AssemblyInfo.cs" -Recurse
        $filename | %{
         (gc $_) -replace "0.0.0.0", "$(VERSION_NUMBER)" |Set-Content $_.fullname
        }
        (Get-Content "$(Agent.BuildDirectory)\s\origam-source\Origam.ServerCore\Controller\AboutController.cs") -replace "Placeholder to be changed at build time", "$(VERSION_NUMBER)" | Set-Content "$(Agent.BuildDirectory)\s\origam-source\Origam.ServerCore\Controller\AboutController.cs"
       displayName: 'Build Number'
     - task: VSBuild@1
       displayName: 'Build Architect'
       inputs:
         solution: '$(Agent.BuildDirectory)/s/origam-source/**/*.sln'
         platform: 'Any CPU'
         configuration: 'Release Architect'
         msbuildArchitecture: 'x64'
     - task: VSTest@2
       displayName: 'Run Tests'
       inputs:
         testSelector: 'testAssemblies'
         testAssemblyVer2: |
           **\*test*.dll
           !**\*TestAdapter.dll
           !**\obj\**
         searchFolder: '$(Agent.BuildDirectory)\s\origam-source\'
     - task: CopyFiles@2
       displayName: 'Copy OrigamScheduler to: $(build.artifactstagingdirectory)\origam-architect'
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-source\OrigamScheduler\bin\Release\'
         Contents: |
           **\*.dll
           **\*.exe
           **\*.pdb
         TargetFolder: '$(build.artifactstagingdirectory)\origam-architect'
       condition: succeededOrFailed()
     - task: CopyFiles@2
       displayName: 'Copy Architect to: $(build.artifactstagingdirectory)\origam-architect'
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-source\OrigamArchitect\bin\Release\'
         Contents: |
           **\*.dll
           **\*.exe
           **\*.pdb
         TargetFolder: '$(build.artifactstagingdirectory)\origam-architect'
       condition: succeededOrFailed()
     - task: CopyFiles@2
       displayName: 'Copy External Architect Dlls to: $(build.artifactstagingdirectory)\origam-architect'
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-source\'
         Contents: 'EnterpriseLibrary\Interop.MSCommLib.dll'
         TargetFolder: '$(build.artifactstagingdirectory)\origam-architect'
         flattenFolders: true
       condition: succeededOrFailed()
     - task: PublishBuildArtifacts@1
       displayName: 'Publish Artifact: origam-architect'
       inputs:
         PathtoPublish: '$(build.artifactstagingdirectory)\origam-architect'
         ArtifactName: origam-architect
       condition: succeededOrFailed()
     - task: VSBuild@1
       displayName: 'Build Client'
       inputs:
         solution: '$(Agent.BuildDirectory)/s/origam-source/**/*.sln'
         platform: 'Any CPU'
         configuration: 'Release Client'
         msbuildArchitecture: 'x64'
     - task: CopyFiles@2
       displayName: 'Copy OrigamScheduler to: $(build.artifactstagingdirectory)\origam-client'
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-source\OrigamScheduler\bin\Release\'
         Contents: |
           **\*.dll
           **\*.exe
           **\*.pdb
         TargetFolder: '$(build.artifactstagingdirectory)\origam-client'
       condition: succeededOrFailed()
     - task: CopyFiles@2
       displayName: 'Copy Client to: $(build.artifactstagingdirectory)\origam-client'
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-source\OrigamArchitect\bin\Release\'
         Contents: |
           **\*.dll
           **\*.exe
           **\*.pdb
         TargetFolder: '$(build.artifactstagingdirectory)\origam-client'
       condition: succeededOrFailed()
     - task: PublishBuildArtifacts@1
       displayName: 'Publish Artifact: origam-client'
       inputs:
         PathtoPublish: '$(build.artifactstagingdirectory)\origam-client'
         ArtifactName: origam-client
       condition: succeededOrFailed()
     - task: DeleteFiles@1
       inputs:
         SourceFolder: '$(build.artifactstagingdirectory)\origam-client'
         Contents: |
           **\*.*
         RemoveSourceFolder: true
       displayName: 'origam-client clean up'
     - task: VSBuild@1
       displayName: 'Build Server'
       inputs:
         solution: '$(Agent.BuildDirectory)/s/origam-source/**/*.sln'
         platform: 'Any CPU'
         configuration: 'Release Server'
         msbuildArchitecture: 'x64'
     - task: MSBuild@1
       displayName: 'Build LDAPMembershipProvider'
       inputs:
         solution: $(Agent.BuildDirectory)/s/origam-source/ORIGAMMembershipProvider/LDAPMembershipProvider.csproj
         msbuildArchitecture: x64
         configuration: 'Release Server'
     - task: CopyFiles@2
       displayName: 'Copy Server Dlls to: $(build.artifactstagingdirectory)\origam-web\bin'
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-source\Origam.Server\bin\Release\'
         Contents: |
           **\*.dll
           **\*.pdb
           **\*.exe
           !**\Microsoft.AspNetCore.Http.Abstractions.dll
           !**\Microsoft.Extensions.Configuration.Abstractions.dll
           !**\Microsoft.Extensions.Logging.Abstractions.dll
         TargetFolder: '$(build.artifactstagingdirectory)\origam-web\bin'
       condition: succeededOrFailed()
     - task: CopyFiles@2
       displayName: 'Copy External Dlls to: $(build.artifactstagingdirectory)\origam-web\bin'
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-source\'
         Contents: |
           EnterpriseLibrary\FluorineFx.dll
           EnterpriseLibrary\Interop.MSCommLib.dll
           EnterpriseLibrary\Microsoft.AspNet.Identity.Owin.dll
           OrigamMembershipProvider\bin\Release\LDAPMembershipProvider.dll
           OrigamMembershipProvider\bin\Release\LDAPMembershipProvider.pdb
         TargetFolder: '$(build.artifactstagingdirectory)\origam-web\bin'
         flattenFolders: true
       condition: succeededOrFailed()
     - task: CopyFiles@2
       displayName: 'Copy Web Files to: $(build.artifactstagingdirectory)\origam-web'
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-source\web'
         Contents: |
           css\**\*.*
           assets\**\*.*
           upgrade\**\*.*
           js\**\*.*
           bin\*.dll
           WEB-INF\**\*.*
           *
           !*.config
           !*.swf
           !*.aspx
         TargetFolder: '$(build.artifactstagingdirectory)\origam-web'
       condition: succeededOrFailed()
     - powershell: |
        $source = "$(Agent.BuildDirectory)\s\origam-source\web\App_Code\Startup.cs"; $destination = "$(build.artifactstagingdirectory)\origam-web\App_Code\Startup.cs_"
        # Create the folder structure and empty destination file, similar to
        # the Unix 'touch' command
        New-Item -ItemType File -Path $destination -Force
        Copy-Item $source $destination -Force
       displayName: 'Copy Startup.cs'
     - powershell: |
        Copy-Item $(Agent.BuildDirectory)\s\origam-source\web\Portal.swf $(build.artifactstagingdirectory)\origam-web\Portal_$(VERSION_NUMBER).swf
        Copy-Item $(Agent.BuildDirectory)\s\origam-source\web\Portal_dbg.swf $(build.artifactstagingdirectory)\origam-web\Portal_$(VERSION_NUMBER)_dbg.swf
        Copy-Item $(Agent.BuildDirectory)\s\origam-source\web\theme.swf $(build.artifactstagingdirectory)\origam-web\theme_$(VERSION_NUMBER).swf
        Copy-Item $(Agent.BuildDirectory)\s\origam-source\web\theme.swf $(build.artifactstagingdirectory)\origam-web\theme.swf
        $buildNumber = $($env:OrigamBuildNumber)
        $config = "<appPortalSettings><add key=`"swfFile`" value=`"Portal_$(VERSION_NUMBER)`"/><add key=`"themeFile`" value=`"theme_$(VERSION_NUMBER)`"/></appPortalSettings>"
        $config|Set-Content $(build.artifactstagingdirectory)\origam-web\portal.config
       displayName: 'Copy Flash UI'
     - task: PublishBuildArtifacts@1
       displayName: 'Publish Artifact: origam-web'
       inputs:
         PathtoPublish: '$(build.artifactstagingdirectory)\origam-web'
         ArtifactName: origam-web
       condition: succeededOrFailed()
     - powershell: |
        (Get-Content $(Agent.BuildDirectory)\s\origam-source\OrigamSetup\ArchitectSetup.wxs).replace("SWF-BUILDNUMBER", "$(VERSION_NUMBER)") | Set-Content $(Agent.BuildDirectory)\s\origam-source\OrigamSetup\ArchitectSetup.wxs
        (Get-Content $(Agent.BuildDirectory)\s\origam-source\OrigamSetup\ArchitectSetup.wxs).replace("@branch@", "$(BRANCH)") | Set-Content $(Agent.BuildDirectory)\s\origam-source\OrigamSetup\ArchitectSetup.wxs
       displayName: 'Prepare ArchitectSetup.wxs'
     - powershell: |
        xcopy $(Agent.BuildDirectory)\s\origam-model\l10n model_template\l10n /i /e /y
        xcopy $(Agent.BuildDirectory)\s\origam-model\model model_template\model /i /e /y
        & { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::CreateFromDirectory('model_template', '$(Agent.BuildDirectory)\s\origam-source\OrigamSetup\model_root_source\DefaultModel.zip'); }
        xcopy model_template $(build.artifactstagingdirectory)\origam-model /i /e /y
        xcopy $(build.artifactstagingdirectory)\origam-architect $(Agent.BuildDirectory)\s\origam-source\OrigamSetup\source /i /e /y
        xcopy $(build.artifactstagingdirectory)\origam-web $(Agent.BuildDirectory)\s\origam-source\OrigamSetup\server_source /i /e /y
       displayName: 'Prepare Sources for Setup (Model)'
     - powershell: |
        & "$(WIX)bin\candle.exe" -ext WixSqlExtension -ext WixUtilExtension ArchitectSetup.wxs
        & "$(WIX)bin\light.exe" -ext WixSqlExtension -ext WixUtilExtension -ext WixNetFxExtension -sice:ICE20 -cultures:en-us -loc resources.en-us.wxl -out OrigamSetup.msi ArchitectSetup.wixobj
        New-Item -ItemType File -Path $(build.artifactstagingdirectory)\origam-setup\OrigamSetup.msi -Force
        Copy-Item OrigamSetup.msi $(build.artifactstagingdirectory)\origam-setup\OrigamSetup.msi -Force
       workingDirectory: $(Agent.BuildDirectory)\s\origam-source\OrigamSetup
       displayName: 'Build Setup'
     - task: PublishBuildArtifacts@1
       displayName: 'Publish Artifact: origam-setup'
       inputs:
         PathtoPublish: '$(build.artifactstagingdirectory)\origam-setup'
         ArtifactName: origam-setup
       condition: succeededOrFailed()
     - task: DeleteFiles@1
       inputs:
         SourceFolder: '$(build.artifactstagingdirectory)\origam-architect'
         Contents: |
           **\*.*
         RemoveSourceFolder: true
       displayName: 'origam-architect clean up'
     - task: DeleteFiles@1
       inputs:
         SourceFolder: '$(build.artifactstagingdirectory)\origam-web'
         Contents: |
           **\*.*
         RemoveSourceFolder: true
       displayName: 'origam-web clean up'
     - task: DeleteFiles@1
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-source\OrigamSetup'
         Contents: |
           source\**\*.*
           server_source\**\*.*
         RemoveSourceFolder: true
       displayName: 'origam-setup clean up'
     - script: |
        set MsBuildEmitSolution=1
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe" $(Agent.BuildDirectory)\s\origam-source\Origam.sln /pp -v:m
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe" $(Agent.BuildDirectory)\s\origam-source\Origam.sln /p:Configuration="Release Server" /t:Server\Origam_ServerCore:Publish -v:m
       displayName: 'Build HTML Server'
     - task: CopyFiles@2
       displayName: 'Copy HTML Server to: $(build.artifactstagingdirectory)\origam-html'
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-source\Origam.ServerCore\bin\Release\net5.0\publish\'
         Contents: |
           **\*.*
           !*.config
         TargetFolder: '$(build.artifactstagingdirectory)\origam-html'
       condition: succeededOrFailed()
     - task: DeleteFiles@1
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-source\'
         Contents: |
           **/bin/*
           **/obj/*
         RemoveSourceFolder: false
       displayName: 'Complete origam-source clean up'
     - script: |
        yarn --frozen-lockfile
       workingDirectory: $(Agent.BuildDirectory)\s\origam-html\
       displayName: 'origam-html yarn'
     - script: |
        yarn build
       workingDirectory: $(Agent.BuildDirectory)\s\origam-html\
       displayName: 'origam-html yarn build'
     - task: CopyFiles@2
       displayName: 'HTML Client to: $(build.artifactstagingdirectory)\origam-html'
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-html\build'
         TargetFolder: '$(build.artifactstagingdirectory)\origam-html\clients\origam'
     - script: |
        yarn --frozen-lockfile
       workingDirectory: $(Agent.BuildDirectory)\s\origam-html-chat\client
       displayName: 'origam-html-chat yarn'
     - script: |
        yarn build
       workingDirectory: $(Agent.BuildDirectory)\s\origam-html-chat\client
       displayName: 'origam-html-chat yarn build'
     - task: CopyFiles@2
       displayName: 'HTML Chat to: $(build.artifactstagingdirectory)\origam-html'
       inputs:
         SourceFolder: '$(Agent.BuildDirectory)\s\origam-html-chat\client\build'
         TargetFolder: '$(build.artifactstagingdirectory)\origam-html\clients\chat'
     - task: PublishBuildArtifacts@1
       displayName: 'Publish Artifact: origam-html'
       inputs:
         PathtoPublish: '$(build.artifactstagingdirectory)\origam-html'
         ArtifactName: origam-html
       condition: succeededOrFailed()
     - task: GitHubRelease@1
       inputs:
         gitHubConnection: 'https://github.com/origam/'
         repositoryName: 'origam/origam-source'
         action: 'delete'
         tag: '$(TAG)'
       displayName: Delete previous GitHub release
       continueOnError: true
     - script: |
        git tag -f $(TAG)
        git push -f origin $(TAG)
       workingDirectory: $(Agent.BuildDirectory)\s\origam-source
       displayName: 'Tag origam-source with $(TAG)'
     - script: |
        git tag -f $(TAG)
        git push -f origin $(TAG)
       workingDirectory: $(Agent.BuildDirectory)\s\origam-html
       displayName: 'Tag origam-html with $(TAG)'
     - powershell: |
        & { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::CreateFromDirectory("$(Build.ArtifactStagingDirectory)\origam-html", "$(build.artifactstagingdirectory)\origam-html.zip"); }
        & { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::CreateFromDirectory("$(Agent.BuildDirectory)\s\origam-model", "$(build.artifactstagingdirectory)\origam-model.zip"); }
       displayName: Zip files for release
     - task: GitHubRelease@1
       inputs:
         gitHubConnection: 'https://github.com/origam/'
         repositoryName: 'origam/origam-source'
         action: 'create'
         target: $(ORIGAM_SOURCE_COMMIT_ID)
         tagSource: 'userSpecifiedTag'
         tag: '$(TAG)'
         title: '$(TAG)'
         releaseNotesSource: 'inline'
         releaseNotesInline: 'The latest master build.'
         assets: |
           $(Build.ArtifactStagingDirectory)/origam-model.zip
           $(Build.ArtifactStagingDirectory)/origam-html.zip
           $(Build.ArtifactStagingDirectory)/origam-setup/OrigamSetup.msi
         addChangeLog: false
       displayName: Create new GitHub release
  - job: BuildDocker
    displayName: Build Docker
    dependsOn: BuildOrigam
    pool:
      vmImage: ubuntu-16.04
    steps:
     - checkout: origam-source
       fetchDepth: 1
     - bash: |
        origamBuildNumber=$(($(Build.BuildId) + 5300))
        wget `wget -nv -O - "https://dev.azure.com/origam/Origam%20Builds/_apis/build/builds/$(Build.BuildId)/artifacts?artifactName=origam-html&api-version=5.0" | sed 's|"|\n|g' | grep zip` -O origam-html.zip
        unzip -qq origam-html.zip
        echo "##vso[task.setvariable variable=OrigamBuildNumber;]$origamBuildNumber"
       workingDirectory: '$(Agent.BuildDirectory)/s/OrigamDocker'
       displayName: Download origam-html artifact
     - task: Docker@2
       displayName: 'Build and publish docker image'
       inputs:
         containerRegistry: dockerhub
         repository: origam/server
         Dockerfile: '$(Agent.BuildDirectory)/s/OrigamDocker/Dockerfile'
         buildContext: '$(Agent.BuildDirectory)/s/OrigamDocker'
         tags: |
           $(BRANCH)-latest
           $(BRANCH)-$(OrigamBuildNumber)